"""Published benchmark and leaderboard data for the macro placement challenge."""

from __future__ import annotations

from typing import Dict, List


IBM_BENCHMARKS: List[str] = [
    "ibm01",
    "ibm02",
    "ibm03",
    "ibm04",
    "ibm06",
    "ibm07",
    "ibm08",
    "ibm09",
    "ibm10",
    "ibm11",
    "ibm12",
    "ibm13",
    "ibm14",
    "ibm15",
    "ibm16",
    "ibm17",
    "ibm18",
]


SA_BASELINES: Dict[str, float] = {
    "ibm01": 1.3166,
    "ibm02": 1.9072,
    "ibm03": 1.7401,
    "ibm04": 1.5037,
    "ibm06": 2.5057,
    "ibm07": 2.0229,
    "ibm08": 1.9239,
    "ibm09": 1.3875,
    "ibm10": 2.1108,
    "ibm11": 1.7111,
    "ibm12": 2.8261,
    "ibm13": 1.9141,
    "ibm14": 2.2750,
    "ibm15": 2.3000,
    "ibm16": 2.2337,
    "ibm17": 3.6726,
    "ibm18": 2.7755,
}


REPLACE_BASELINES: Dict[str, float] = {
    "ibm01": 0.9976,
    "ibm02": 1.8370,
    "ibm03": 1.3222,
    "ibm04": 1.3024,
    "ibm06": 1.6187,
    "ibm07": 1.4633,
    "ibm08": 1.4285,
    "ibm09": 1.1194,
    "ibm10": 1.5009,
    "ibm11": 1.1774,
    "ibm12": 1.7261,
    "ibm13": 1.3355,
    "ibm14": 1.5436,
    "ibm15": 1.5159,
    "ibm16": 1.4780,
    "ibm17": 1.6446,
    "ibm18": 1.7722,
}


README_LEADERBOARD: List[Dict[str, object]] = [
    {
        "rank": 1,
        "team": '"Mike Gao" (autoresearch)',
        "avg_proxy_cost": 1.3255,
        "best": None,
        "worst": None,
        "overlaps": 0,
        "runtime": "16min/bench",
        "verified": False,
        "notes": "",
    },
    {
        "rank": 2,
        "team": '"MTK" (DreamPlace++)',
        "avg_proxy_cost": 1.3622,
        "best": 1.0040,
        "worst": 1.6710,
        "overlaps": 0,
        "runtime": "112s/bench (GPU)",
        "verified": True,
        "notes": "Verified better than self-reported 1.3998; faster GPU on eval hardware",
    },
    {
        "rank": 3,
        "team": '"Electric Beatel" (ePlace-Lite)',
        "avg_proxy_cost": 1.3913,
        "best": 0.9773,
        "worst": 1.7253,
        "overlaps": 0,
        "runtime": "155s/bench (GPU)",
        "verified": True,
        "notes": "",
    },
    {
        "rank": 4,
        "team": '"Varun\'s Parallel Worlds" (GRPlace)',
        "avg_proxy_cost": 1.4017,
        "best": 1.0362,
        "worst": 1.7298,
        "overlaps": 0,
        "runtime": "27s/bench",
        "verified": True,
        "notes": "",
    },
    {
        "rank": 5,
        "team": '"UT Austin" - AS (DREAMPlace Analytical)',
        "avg_proxy_cost": 1.4076,
        "best": None,
        "worst": None,
        "overlaps": 0,
        "runtime": "17s/bench",
        "verified": False,
        "notes": "",
    },
    {
        "rank": 6,
        "team": '"ByteDancer" (Incremental CD)',
        "avg_proxy_cost": 1.4151,
        "best": 1.0236,
        "worst": 1.7792,
        "overlaps": 0,
        "runtime": "38min/bench",
        "verified": True,
        "notes": "",
    },
    {
        "rank": 7,
        "team": '"BakaBobo" (Spread+Refine)',
        "avg_proxy_cost": 1.4403,
        "best": None,
        "worst": None,
        "overlaps": 0,
        "runtime": "212s/bench",
        "verified": False,
        "notes": "",
    },
    {
        "rank": 8,
        "team": '"another Waterloo kid" (Batched Nesterov GP)',
        "avg_proxy_cost": 1.4568,
        "best": None,
        "worst": None,
        "overlaps": 0,
        "runtime": "118s/bench",
        "verified": False,
        "notes": "",
    },
    {
        "rank": None,
        "team": "RePlAce (baseline)",
        "avg_proxy_cost": 1.4578,
        "best": 0.9976,
        "worst": 1.8370,
        "overlaps": 0,
        "runtime": "—",
        "verified": True,
        "notes": "",
    },
    {
        "rank": 9,
        "team": '"UTAUSTIN-CT" (PLC-Exact Congestion-Aware SA)',
        "avg_proxy_cost": 1.5062,
        "best": None,
        "worst": None,
        "overlaps": 0,
        "runtime": "35s/bench",
        "verified": False,
        "notes": "",
    },
    {
        "rank": 10,
        "team": '"oracleX" (Oracle)',
        "avg_proxy_cost": 1.5130,
        "best": None,
        "worst": None,
        "overlaps": 0,
        "runtime": "3min/bench",
        "verified": False,
        "notes": "",
    },
    {
        "rank": 11,
        "team": '"CA" (congestion_aware)',
        "avg_proxy_cost": 1.5238,
        "best": None,
        "worst": None,
        "overlaps": 0,
        "runtime": "13s/bench",
        "verified": False,
        "notes": "",
    },
    {
        "rank": 12,
        "team": '"#5 ubc cpen student" (Gene Pool Shuffle)',
        "avg_proxy_cost": 1.5337,
        "best": 1.1411,
        "worst": 1.8084,
        "overlaps": 0,
        "runtime": "13s/bench",
        "verified": True,
        "notes": "",
    },
    {
        "rank": 13,
        "team": "Will Seed (Partcl)",
        "avg_proxy_cost": 1.5338,
        "best": 1.1625,
        "worst": 1.7965,
        "overlaps": 0,
        "runtime": "35s total",
        "verified": True,
        "notes": "",
    },
    {
        "rank": 14,
        "team": '"Cezar" (CRISP)',
        "avg_proxy_cost": 1.5781,
        "best": 1.1896,
        "worst": 1.8520,
        "overlaps": 0,
        "runtime": "4min/bench",
        "verified": True,
        "notes": "",
    },
    {
        "rank": 15,
        "team": '"UT Austin" - RH (DREAMPlace)',
        "avg_proxy_cost": 1.6037,
        "best": None,
        "worst": None,
        "overlaps": 0,
        "runtime": "4.5s/bench",
        "verified": False,
        "notes": "",
    },
    {
        "rank": 16,
        "team": '"UT Austin" - CT (PROXYCost)',
        "avg_proxy_cost": 1.8706,
        "best": None,
        "worst": None,
        "overlaps": 0,
        "runtime": "187s/bench",
        "verified": False,
        "notes": "",
    },
    {
        "rank": None,
        "team": "SA (baseline)",
        "avg_proxy_cost": 2.1251,
        "best": 1.3166,
        "worst": 3.6726,
        "overlaps": 0,
        "runtime": "—",
        "verified": True,
        "notes": "",
    },
    {
        "rank": None,
        "team": "Greedy Row (demo)",
        "avg_proxy_cost": 2.2109,
        "best": 1.6728,
        "worst": 2.7696,
        "overlaps": 0,
        "runtime": "0.3s total",
        "verified": True,
        "notes": "",
    },
]


def leaderboard_rows(include_non_ranked: bool = True) -> List[Dict[str, object]]:
    """Return the README leaderboard rows, optionally filtering non-ranked rows."""

    if include_non_ranked:
        return list(README_LEADERBOARD)
    return [row for row in README_LEADERBOARD if row["rank"] is not None]


def leaderboard_rank_for_score(avg_proxy_cost: float) -> int:
    """Compute the insertion rank for a score against the README leaderboard."""

    rows = [row for row in README_LEADERBOARD if isinstance(row.get("avg_proxy_cost"), (int, float))]
    better = sum(1 for row in rows if float(row["avg_proxy_cost"]) < avg_proxy_cost)
    return better + 1
